// Generated by `wit-bindgen` 0.1.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_MY_WORLD_H
#define __CPP_GUEST_BINDINGS_MY_WORLD_H
#include <cstdint>
namespace my_world {  class ResourceBase{
    protected:
    int32_t handle;
    public:
    ResourceBase(int32_t h=0) : handle(h) {}
//    void set_handle(int32_t h) { handle=h; }
    int32_t get_handle() const { return handle; }
  }; }
namespace test { namespace example { namespace my_interface { class MyObject : my_world::ResourceBase {
  public:
  MyObject(uint32_t a);
  void Set(uint32_t v);
  uint32_t Get();
  ~MyObject();
  MyObject(my_world::ResourceBase&&);
}; }}}
namespace test { namespace example { namespace my_interface { 
}}}

#endif
