// Generated by `wit-bindgen` 0.10.0. DO NOT EDIT!
#include "my_world.h"


__attribute__((__import_module__("test:example/my-interface"), __import_name__("[constructor]my-object")))
int32_t __wasm_import_test_example_my_interface_constructor_my_object(int32_t);

__attribute__((__import_module__("test:example/my-interface"), __import_name__("[method]my-object.set")))
void __wasm_import_test_example_my_interface_method_my_object_set(int32_t, int32_t);

__attribute__((__import_module__("test:example/my-interface"), __import_name__("[method]my-object.get")))
int32_t __wasm_import_test_example_my_interface_method_my_object_get(int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void my_world_borrow_my_object_free(my_world_borrow_my_object_t *ptr) {
  my_world_my_object_drop_borrow(*ptr);
}

void my_world_own_my_object_free(my_world_own_my_object_t *ptr) {
  test_example_my_interface_my_object_drop_own(*ptr);
}

// Functions for working with resource `test:example/my-interface/my-object`
my_world_borrow_my_object_t test_example_my_interface_borrow_my_object(my_world_own_my_object_t arg) {
  return (my_world_borrow_my_object_t) { arg.__handle };
}
__attribute__((__import_module__("test:example/my-interface"), __import_name__("[resource-drop]my-object")))
void __wasm_import_test_example_my_interface_my_object_drop_own(int32_t);

void test_example_my_interface_my_object_drop_own(my_world_own_my_object_t arg) {
  __wasm_import_test_example_my_interface_my_object_drop_own(arg.__handle);
}
__attribute__((__import_module__("test:example/my-interface"), __import_name__("[resource-drop]my-object")))
void __wasm_import_my_world_my_object_drop_borrow(int32_t);

void my_world_my_object_drop_borrow(my_world_borrow_my_object_t arg) {
  __wasm_import_my_world_my_object_drop_borrow(arg.__handle);
}

// Component Adapters

my_world_own_my_object_t test_example_my_interface_constructor_my_object(uint32_t a) {
  int32_t ret = __wasm_import_test_example_my_interface_constructor_my_object((int32_t) (a));
  return (my_world_own_my_object_t) { ret };
}

void test_example_my_interface_method_my_object_set(my_world_borrow_my_object_t self, uint32_t v) {
  __wasm_import_test_example_my_interface_method_my_object_set((self).__handle, (int32_t) (v));
}

uint32_t test_example_my_interface_method_my_object_get(my_world_borrow_my_object_t self) {
  int32_t ret = __wasm_import_test_example_my_interface_method_my_object_get((self).__handle);
  return (uint32_t) (ret);
}

extern void __component_type_object_force_link_my_world(void);
void __component_type_object_force_link_my_world_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_my_world();
}
