// Generated by `wit-bindgen` 0.10.0. DO NOT EDIT!
#ifndef __BINDINGS_MY_WORLD_H
#define __BINDINGS_MY_WORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  int32_t __handle;
} my_world_borrow_my_object_t;

typedef struct {
  int32_t __handle;
} my_world_own_my_object_t;

// Imported Functions from `test:example/my-interface`
my_world_own_my_object_t test_example_my_interface_constructor_my_object(uint32_t a);
void test_example_my_interface_method_my_object_set(my_world_borrow_my_object_t self, uint32_t v);
uint32_t test_example_my_interface_method_my_object_get(my_world_borrow_my_object_t self);

// Helper Functions

void my_world_borrow_my_object_free(my_world_borrow_my_object_t *ptr);
void my_world_own_my_object_free(my_world_own_my_object_t *ptr);

// Functions for working with resource `test:example/my-interface/my-object`
my_world_borrow_my_object_t test_example_my_interface_borrow_my_object(my_world_own_my_object_t);
void test_example_my_interface_my_object_drop_own(my_world_own_my_object_t);
void my_world_my_object_drop_borrow(my_world_borrow_my_object_t);

#ifdef __cplusplus
}
#endif
#endif
