// Generated by `wit-bindgen` 0.1.0. DO NOT EDIT!
#ifndef __CPP_HOST_BINDINGS_MY_WORLD_H
#define __CPP_HOST_BINDINGS_MY_WORLD_H
#include <cstdint>
namespace my_world {  class ResourceBase{
    public:
    int32_t id;
    virtual ~ResourceBase();
    ResourceBase();
    static ResourceBase* lookup_resource(int32_t id);
  }; 
  template <typename T> struct Owned{
    T *ptr;
  }; }
namespace test { namespace example { namespace my_interface { class MyObject : public my_world::ResourceBase {
  // private implementation data
  struct pImpl;
  pImpl * p_impl;
  public:
  ~MyObject();
  MyObject(uint32_t a);
  void Set(uint32_t v);
  uint32_t Get();
}; }}}
namespace test { namespace example { namespace my_interface { 
}}}
extern "C" void register_my_world();

#endif
